feature/signup
pedrozs/target pull request #1
Opened 2018-09-21 18:36 UTC by pedrozs

## feature/signup
### Description
This PR adds a signup page. It validates the form and shows error messages. Missing fields are highlighted in red.
## Screenshots

## Page
![page](https://user-images.githubusercontent.com/39418440/45899476-5359f480-bdb3-11e8-95cd-74af6e5efa91.png)
---------
## Validation
![validation](https://user-images.githubusercontent.com/39418440/45899497-62d93d80-bdb3-11e8-89ab-7c1ba02d5946.png)
---------
## Error
![error](https://user-images.githubusercontent.com/39418440/45899508-6a004b80-bdb3-11e8-8222-8a994d767c8c.png)

2018-09-21 18:52 UTC, felipegarcia92 requested changes

2018-09-21 18:52 UTC, felipegarcia92 commented on src/components/common/Input.js
> +// import { FormattedMessage } from 'react-intl';
Remove commented lines

2018-09-21 18:52 UTC, felipegarcia92 commented on src/components/user/LoginForm.js
> +    <div className="topLeft">
In CSS you normally write the class names with hyphens instead of camel case. In this case: `top-left`.

2018-09-21 18:52 UTC, felipegarcia92 commented on src/components/user/SignUpForm.js
> +          placeholder="SELECT YOUR GENDER"
Shouldn't this go through the intl package to get translated?

2018-09-21 18:52 UTC, felipegarcia92 commented on src/styles/loginSignupPage.scss
> +.loginPage,
Convert to `.this-style`

2018-09-21 18:52 UTC, felipegarcia92 commented on src/styles/loginSignupPage.scss
>      color: #212121;
Better to move to a constants file in SCSS and import them, you may want to reuse these

2018-09-21 18:52 UTC, felipegarcia92 commented on src/utils/constraints.js
>  export const signUp = {
You should add a presence validator and even validate the content of the `gender` field.

2018-09-24 13:25 UTC, xlasserre requested changes
Nice job!! I left just a few comments.

2018-09-24 13:25 UTC, xlasserre commented on src/components/user/SignUpForm.js
> +          name="password_confirmation"
Here I would also use a hyphen, instead of an underscore.

2018-09-24 13:25 UTC, xlasserre commented on src/containers/HomePage.js
> +  logout: object,
Is logout an object?

2018-09-24 13:25 UTC, xlasserre commented on src/locales/en.js
> +  'name.presence': 'You must enter a name continue',
There is a missing 'to' between 'name' and 'continue'

2018-09-24 14:55 UTC, pedrozs commented on src/components/user/SignUpForm.js
> +          name="password_confirmation"
It's the name of the json field that goes through the api, it must stay that way.

2018-09-24 15:44 UTC, fedeagripa reviewed
Check usage of units of measure (px, rem, em). Try to use one (usually rem) when possible

2018-09-24 15:44 UTC, fedeagripa commented on src/styles/loginSignupPage.scss
> +    margin-top: 6px;
Please unify margins and use one unit of measure `margin: .6rem 1rem 0 0;`

2018-09-24 18:42 UTC, xlasserre approved these changes
👌 I left two more comments but you decide if they are worth to change. They are kind of small to request more changes.

2018-09-24 18:42 UTC, missx commented on src/components/common/Select.js
> +const { string, object, array } = PropTypes;
You could also import these 3 types instead of importing all PropTypes library.

2018-09-24 18:42 UTC, missx commented on src/components/user/LoginForm.js
> +    <p className="target-description">Create a  target  wherever on the map, specify your interest: Travel, Dating, Music, etc and start conecting with others who share your interest.</p>
This line is too long, could you shorten it?

2018-09-24 18:44 UTC, fedeagripa approved these changes

2018-09-24 19:33 UTC, merged