Testing
pedrozs/target pull request #8
Opened 2018-10-12 13:51 UTC by pedrozs

This solves a problem with tests and adds a test for the signup page.

2018-10-12 19:31 UTC, felipegarcia92 requested changes
Good job on the tests, specially the SignUpPage ones 👍

2018-10-12 19:31 UTC, felipegarcia92 commented on src/containers/HomePage.spec.js
> +// import nock from 'nock';
Remove commented code

2018-10-12 19:31 UTC, felipegarcia92 commented on src/containers/HomePage.spec.js
> +  it('should render a div', () => {
`a div`? There are many divs, maybe you should specify that you're looking for an specific root div tag.

2018-10-12 19:31 UTC, felipegarcia92 commented on src/containers/HomePage.spec.js
> +describe('<HomePage />', () => {
This spec is a little vague. What do we expect to see when arriving to the homepage? One left menu component and a map component, right? Can you test on the presence of those?

2018-10-12 19:31 UTC, felipegarcia92 commented on src/containers/SignUpPage.spec.js
> +    // sessionService.loadSession = jest.fn(() => Promise.reject('Session not found'));
Remove commented code

2018-10-12 19:31 UTC, felipegarcia92 commented on src/containers/SignUpPage.spec.js
> +      const inp = gender.find('input').at(0);
`inp` doesn't say much. `genderInput` maybe?  `genderSelect`?

2018-10-15 14:55 UTC, felipegarcia92 approved these changes
👌

2018-10-16 14:06 UTC, juanlacu approved these changes
Good work on this one!

2018-10-16 14:14 UTC, merged